apiVersion: v1
kind: Namespace
metadata:
  name: myserver
---
apiVersion: v1
kind: LimitRange
metadata:
  name: myserver
  namespace: myserver
spec:
  limits:
  - type: Container
    defaultRequest:
      memory: 90Mi
      cpu: 100m
    default:
      memory: 90Mi
      cpu: 100m
    maxLimitRequestRatio: 
      cpu: 2              
      memory: 2         
