apiVersion: v1
data:
  default.conf: |
      ##
      # Virtual Host Configs
      ##
      server {
        listen 80 default_server;
        server_name _;
        root /usr/share/nginx/html/;

        location / {
          if (!-e $request_filename) {
            rewrite ^/(.*) /index.html last;
          }
          try_files $uri $uri/ =404;
        }
        location /health {
            access_log off;
                return 200;
        }
        # pass jsp scripts to tomcat server
        #    location ~ \.jsp$ {
        #         proxy_pass  http://tomcat_webserver;
        #         proxy_set_header   Host    $host;
        #         proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        #         proxy_set_header X-Real-IP $remote_addr;
        #    }
      }

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: myapp-nginx-conf
  namespace: myserver
